
# ------------------------------------------------------------------------------
# packages installation

- name: "[prepare] - add required apt packages"
  become: yes
  apt:
    name: "{{ package }}"
    update_cache: yes
  loop:
    - git
  loop_control:
    loop_var: package

# ------------------------------------------------------------------------------
# cagette installation

- name: "[cagette-sources] - add haxe packages required"
  become: yes
  npm:
    name: "{{ package }}"
    global: yes
  loop:
    - lix
    - haxe-modular
  loop_control:
    loop_var: package

- name: "[cagette-sources] - create {{ group }} group"
  become: yes
  group:
    name: "{{ group }}"

- name: "[cagette-sources] - create {{ user }} user"
  become: yes
  user:
    name: "{{ user }}"
    comment: system account for cagette webapp
    group: "{{ group }}"

- name: "[cagette-sources] - create cagette webapp directory"
  become: yes
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: "[cagette-sources] - check for cagette source code presence"
  stat:
    path: "{{ install_directory }}"
  register: cagette_source
  failed_when: no
  changed_when: no

- block:
  - name: "[cagette-sources] - download git source code"
    become: yes
    git:
      repo: "{{ source_repository }}"
      dest: /tmp/cagette
#
  - name: "[cagette-sources] - copy source code to apache directory"
    become: yes
    copy:
      src: /tmp/cagette/docker/app/
      dest: "{{ install_directory }}"
      owner: "{{ user }}"
      group: "{{ group }}"
      remote_src: yes

  - name: "[cagette-sources] - remote git repository from /tmp"
    become: yes
    file:
      path: /tmp/cagette
      state: absent
  when: not cagette_source.stat.exists or (force_source is defined and force_source == "yes")
