
- name: "[cagette-dependencies-backend] - remove cagette-pro plugin"
  become: yes
  file:
    path: "{{ install_directory }}/backend/haxe_libraries/cagette-pro.hxml"
    state: absent

- name: "[cagette-dependencies-backend] - check for backend libraries presence"
  become: yes
  stat:
    path: /root/haxe/haxe_libraries/asys
  register: haxe_backend_libraries
  failed_when: no
  changed_when: no

- name: "[cagette-dependencies-backend] - download required haxe librairies for backend"
  become: yes
  shell: lix download
  args:
    chdir: "{{ install_directory }}/backend"
    executable: /bin/bash
  when: not haxe_backend_libraries.stat.exists or (force_haxe_backend_libraries is defined and force_haxe_backend_libraries == "yes")
