
- name: preflight checks
  include: preflight.yml
  # tags: always

- name: install npm to make cagette work
  include: webapp/npm.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-npm

- name: cagette webapp sources
  include: webapp/sources.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-sources

- name: cagette webapp templo
  include: webapp/templo.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-templo

- name: cagette webapp dependencies for backend
  include: webapp/dependencies/backend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-dependencies
    - cagette-webapp-dependencies-backend

- name: cagette webapp dependencies for frontend
  include: webapp/dependencies/frontend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-dependencies
    - cagette-webapp-dependencies-frontend

- name: cagette webapp compile for backend
  include: webapp/compile/backend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-compile
    - cagette-webapp-compile-backend

- name: cagette webapp compile for backend
  include: webapp/compile/frontend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-compile
    - cagette-webapp-compile-frontend

- name: cagette webapp webserver
  include: webapp/webserver.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-webserver

- name: cagette webapp cron
  include: webapp/cron.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-cron

- name: cagette mailer sources
  include: mailer/sources.yml
  tags:
    - cagette-mailer
    - cagette-mailer-sources
