
- name: preflight checks
  include: preflight.yml

- name: install npm to make cagette work
  include: cagette/npm.yml
  tags:
    - cagette
    - cagette-npm

- name: install cagette source code
  include: cagette/sources.yml
  tags:
    - cagette
    - cagette-sources

- name: install backend dependencies
  include: cagette/dependencies/backend.yml
  tags:
    - cagette
    - cagette-dependencies
    - cagette-dependencies-backend

- name: install frontend dependencies
  include: cagette/dependencies/frontend.yml
  tags:
    - cagette
    - cagette-dependencies
    - cagette-dependencies-frontend

- name: compile backend
  include: cagette/compile/backend.yml
  tags:
    - cagette
    - cagette-compile
    - cagette-compile-backend

- name: compile frontend
  include: cagette/compile/frontend.yml
  tags:
    - cagette
    - cagette-compile
    - cagette-compile-frontend

- name: install webserver
  include: cagette/webserver.yml
  tags:
    - cagette
    - cagette-webserver

- name: install templo
  include: cagette/templo.yml
  tags:
    - cagette
    - cagette-templo

- name: install cron
  include: cagette/cron.yml
  tags:
    - cagette
    - cagette-cron

- name: install mailer
  include: mailer/install.yml
  tags:
    - mailer
    - mailer-install
