
- name: preflight checks
  include: preflight.yml

- name: install npm to make cagette work
  include: webapp/npm.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-npm

- name: install cagette source code
  include: webapp/sources.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-sources

- name: install backend dependencies
  include: webapp/dependencies/backend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-dependencies
    - cagette-webapp-dependencies-backend

- name: install frontend dependencies
  include: webapp/dependencies/frontend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-dependencies
    - cagette-webapp-dependencies-frontend

- name: compile backend
  include: webapp/compile/backend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-compile
    - cagette-webapp-compile-backend

- name: compile frontend
  include: webapp/compile/frontend.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-compile
    - cagette-webapp-compile-frontend

- name: install webserver
  include: webapp/webserver.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-webserver

- name: install templo
  include: webapp/templo.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-templo

- name: install cron
  include: webapp/cron.yml
  tags:
    - cagette
    - cagette-webapp
    - cagette-webapp-cron

- name: install mailer
  include: mailer/install.yml
  tags:
    - cagette-mailer
    - cagette-mailer-install
