---
- name: start cron
  become: yes
  service:
    name: cron
    state: started
    enabled: yes

- name: restart webserver
  become: yes
  service:
    name: apache2
    state: restarted
    enabled: yes
