# ------------------------------------------------------------------------------
# cagette installation - install templo

- name: "[cagette-webapp-templo] - check if templo is installed and available"
  become: yes
  stat:
    path: "{{ ansible_env.HAXE_STD_PATH }}/temploc2"
  register: has_been_installed
  failed_when: no
  changed_when: no

- block:
  - name: "[cagette-webapp-templo] - setup haxelib"
    become: yes
    shell: haxelib setup "{{ ansible_env.HAXE_STD_PATH }}"
    args:
      executable: /bin/bash

  - name: "[cagette-webapp-templo] - install templo"
    become: yes
    shell: haxelib install templo
    args:
      chdir: "{{ ansible_env.HAXE_STD_PATH }}"
      executable: /bin/bash

  - name: "[cagette-webapp-templo] - run templo"
    become: yes
    shell: haxelib run templo
    args:
      chdir: "{{ ansible_env.HAXE_STD_PATH }}"
      executable: /bin/bash

  - name: "[cagette-webapp-templo] - copy temploc2 to /usr/local/bin"
    become: yes
    copy:
      src: /root/haxe/neko/temploc2
      dest: /usr/local/bin/temploc2
      mode: 0755
      remote_src: yes
  when: not has_been_installed.stat.exists or (force_cagette_webapp_templo is defined and force_cagette_webapp_templo == "yes")
