
- name: "[cagette-webapp-webserver] - add apache2 packages"
  become: yes
  apt:
    name: "{{ package }}"
    update_cache: yes
  loop:
    - apache2
    - libapache2-mod-neko
  loop_control:
    loop_var: package
  register: cagette_webapp_webserver_install

- name: "[cagette-webapp-webserver] - enables webserver modules"
  become: yes
  apache2_module:
    state: present
    name: "{{ module }}"
    ignore_configcheck: yes
    force: yes
  loop:
    - ssl
    - rewrite
    - neko
  loop_control:
    loop_var: module
  when: cagette_webapp_webserver_install.changed
  notify:
    - restart webserver

- name: "[cagette-webapp-webserver] - add webserver vhost file"
  become: yes
  template:
    src: templates/vhost.j2
    dest: /etc/apache2/sites-available/cagette.conf
    owner: www-data
    group: www-data
  notify:
    - restart webserver

- name: "[cagette-webapp-webserver] - link vhost file from sites-available to sites-enabled"
  become: yes
  file:
    state: link
    src: /etc/apache2/sites-available/cagette.conf
    dest: /etc/apache2/sites-enabled/cagette.conf
    owner: www-data
    group: www-data
  notify:
    - restart webserver

- meta: flush_handlers
