---
- name: Converge
  hosts: all

  roles:
    - gpenaud.cagette

  environment:
    # cagette
    HAXE_STD_PATH:   /root/haxe/neko
    HAXE_LIBCACHE:   /root/haxe/haxe_libraries
    LD_LIBRARY_PATH: /root/haxe/neko
    NEKOPATH:        /root/haxe/neko
    PATH:            "/root/haxe/:/root/haxe/neko/{{ ansible_env.PATH }}"
