---
- name: Converge
  hosts: all
  become: yes

  vars:
    # mysql
    mysql_root_password: root
    mysql_databases:
      - name: db
        encoding: utf8
        collation: utf8_general_ci
    mysql_users:
      - name: ansible
        host: "%"
        password: ansible
        priv: "db.*:ALL"
    # cagette webapp
    mysql_user: ansible
    mysql_password: ansible
    mysql_db: db

  roles:
    - gpenaud.cagette

  environment:
    # cagette
    HAXE_STD_PATH:   /root/haxe/neko
    HAXE_LIBCACHE:   /root/haxe/haxe_libraries
    LD_LIBRARY_PATH: /root/haxe/neko
    NEKOPATH:        /root/haxe/neko
    PATH:            "/root/haxe/:/root/haxe/neko/{{ ansible_env.PATH }}"
